### ISSUE TITLE
Option to remove .couchapprc file

### ISSUE THREAD

**Issue by commadelimited** [couchapp/couchapp#141]
This might have been asked before, but is there any way we could remove the requirement for having a .couchapprc file in each of our apps?

My company is using couchapp for deploying design docs to Cloudant and it's working great, but it's an irritation for us that we have to have a .couchapprc file in each of our design docs before couchapp will deploy them. Currently the .couchapprc file in **each** of our design docs looks like this:

```
{
    "env": {
        "default": {
            "db": "ignore me"
        }
    }
}
```

This is because we're using a Django settings file to dictate environment, and various other means to identify the url and db name. Like I said, it's just an irritation but when couchapp allows me to push the app even though the .couchapprc file is bogus, perhaps it might be time to allow it to be absent.

Erica for example doesn't require this file...but Erica has other issues.

**Comment by BigBlueHat** [comment]
@commadelimited so...I've been thinking (and dealing) with multiple design docs recently--which is what's brought me back tot his issue.

In re-reading all this, I realize you're looking to avoid having a `.couchapprc` file in your repo (and/or a better place to put one for multiple docs).

If you just don't want the `.couchapprc` file around, delete it. :smiley: Couchapp.py doesn't need it if you pass the URL of the DB in via the command line (vs. reading it out of `.couchapprc`).

You've likely got things sorted out by now. :smile:

**Comment by benoitc** [comment]
actually removing the .couchapprc file will prevent couchapp to know where
the application root is. Right now like Git you can push from anywhere in
the app. Without it you can't.  What is the issue with .couchapprc ?

Also what are the issues with erica?

**Comment by BigBlueHat** [comment]
There's a little bit of new-ish pondering on this topic at #199 

@iblis17 your thoughts here would be most welcome. :smile:
