### ISSUE TITLE
The couchapp website is down

### ISSUE THREAD

**Issue by dgenr8** [couchapp/couchapp#146]

**Comment by BigBlueHat** [comment]
Annnnd....we're back! Sort of. :smile: 

http://couchapp.readthedocs.org/en/latest/ is the new home of the old couchapp.org content and a growing collection of CouchApp & couchapp.py related documentation.

couchapp.org now goes to http://couchdb.apache.org/ where I hope to put up a general pitch for what a CouchApp is and what tools are available.

@iblis17 and @wu-lee get the credit for making this happen. Thanks to you both! :cake:

**Comment by barbalex** [comment]
nice, thanks to all!
