### ISSUE TITLE
default template not found

### ISSUE THREAD

**Issue by gmlevin** [couchapp/couchapp#151]
Installed 1.0.1 on Win7. When I try 
```
couchapp generate app newapp`
```
I get an error that cannot create app because default template is not found. There is no stack trace or path listed. The newapp directory is created and contains subdirectories: `_attachments, views, lists, shows,  updates`, but nothing else. 

If I use
```
couchapp startapp newapp2
```
It succeeds with the same directories as above, but with additional files: `_id, .couchapprc, .couchappignore`.

I tried running 
```
python setup.py test
```
in the couchapp source directory and got no output.

**Comment by BigBlueHat** [comment]
@emkorybski @gmlevin if you're both still around, checkout the updated Windows build here:
https://github.com/couchapp/couchapp/releases/tag/1.0.1

I'm using it now (on Window 10) and `couchapp startapp newapp` works as does `couchapp generate app newapp`.

Though I now find it odd that we have two of these to do the same thing...and don't have `couchapp init`...but that'll be a separate issue.

Reopen this if it's still a problem after trying to the new Windows build.

Cheers!
