### ISSUE TITLE
A todoMVC CouchApp using BackboneJS and Localstorage

### ISSUE THREAD

**Issue by ddgarg** [couchapp/couchapp#155]
Hello,

I Have created a sample couchApp Using Backbone and Localstorage, could you please have a look here [TodoMVC CouchApp](https://github.com/ddgarg/couchdbtodomvc) and let me know if we can put this in couchapp/example.

Thanks.

**Comment by BigBlueHat** [comment]
We don't have an `example` folder as yet, and I'm not quite ready to start one--as I need to think through what the minimal examples would be that highlight using the `couchapp.py` command line tool (vs. building an HTML5 + JS web app that lives in CouchDB).

I'd love it if you could add your example to this list:
https://github.com/couchapp/couchapp/blob/master/docs/couchapp-org/list-of-couchapps.md

Thanks!
