### ISSUE TITLE
Rewrites is addes as a string instead of array

### ISSUE THREAD

**Issue by digitalheir** [couchapp/couchapp#157]
I have `rewrites.js` in my root folder:

```json
[
    {
        "method": "GET",
        "from": "/",
        "to": "aaa/index.html"
    }
]
```

Push the couchapp. Now my ddoc has the following rewrites field:

    "rewrites":"[\r\n    {\r\n        \"method\": \"GET\",\r\n        \"from\": \"/\",\r\n        \"to\": \"aaa/index.html\"\r\n    }\r\n]

Instead of

    "rewrites":[
    {
        "method": "GET",
        "from": "/",
        "to": "aaa/index.html"
    }
    ]

**Comment by BigBlueHat** [comment]
The rewrites file needs to be `rewrites.json` *not* `rewrites.js`--otherwise it's parsed differently.

If you change it to `.json`, you should be fine. :smile:
