### ISSUE TITLE
Couchapp tutorial link is broken

### ISSUE THREAD

**Issue by RichardLitt** [couchapp/couchapp#158]
It points to: https://couchdb.apache.org/page/getting-started

Which gets a 404.

**Comment by wapiflapi** [comment]
Adding to this, FAQ and some other links on the README are broken as well.

**Comment by iblis17** [comment]
Hi @RichardLitt ! 
Here is the doc: https://github.com/couchapp/couchapp/blob/master/docs/index.md

FYI: #146

**Comment by RichardLitt** [comment]
Thanks!

**Comment by BigBlueHat** [comment]
Just merged!

Thanks @iblis17 !
