### ISSUE TITLE
[config.py] unit testing working list

### ISSUE THREAD

**Issue by iblis17** [couchapp/couchapp#176]
Working on class `Config` in `config.py`

- [x] `__init__`
    - PR ~~#177~~
- [x]  `__getitem__`
    - PR ~~#182~~
- [x] `__getattr__`
    - PR ~~#182~~
- [x] `__contains__`
    - PR ~~#183~~
- [x] `__iter__`
    - blocker ~~#173~~
    - PR ~~#215~~
- [x] `get`
    - blocker ~~#174~~
    - PR ~~#175~~
    - [x] test cases: ~~#217~~ 
- [X] `load`
    - PR ~~#193~~ 
    - [X] issue ~~#219~~, PR ~~#220~~
- [x] `local_load`
    - PR ~~#195~~ 
- [X] `update`
    - PR ~~#201~~ 
- [x] `extensions`
    - PR ~~#203~~ 
- [x] `hooks`
    - PR ~~#205~~
    - PR ~~#209~~ 
- [x] `get_db`
    - test
        - [x] PR ~~#211~~
        - [x] PR ~~#212~~ 
    - [x] code refinement: #213
- [x] `get_app_name`
    - bug ~~#179~~
    - PR ~~#214~~

**Comment by iblis17** [comment]
Ops! Sorry, i accidentally close this issue.

Now, I completed the most of test cases.
As the first PR (#177) merged, I will send the PR for next function.

**Comment by BigBlueHat** [comment]
@iblis17 thanks so much for your thoroughness here! It's great to see this code getting cleaned up and the way you're tracking the work is fabulous!

Much thanks! :smile_cat:

**Comment by iblis17** [comment]
All the patches merged :tada: :fireworks:
