### ISSUE TITLE
Windows bundle for 1.0.1

### ISSUE THREAD

**Issue by broerse** [couchapp/couchapp#191]
I am willing create the 1.0.1 standalone bundle for windows. Are there some instructions on how this is done?

**Comment by iblis17** [comment]
Hi @broerse !
Please checkout the PR #187 and the branch in my fork

Also, there is some docs at `resources/win32` :smile:

**Comment by broerse** [comment]
Thanks. I will try it.

**Comment by broerse** [comment]
Almost there. I get:

```
C:\dev\couchapp>python setup.py py2exe -b 2
running py2exe
running build_py
running egg_info
writing requirements to Couchapp.egg-info\requires.txt
writing Couchapp.egg-info\PKG-INFO
writing top-level names to Couchapp.egg-info\top_level.txt
writing dependency_links to Couchapp.egg-info\dependency_links.txt
reading manifest file 'Couchapp.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'Couchapp.egg-info\SOURCES.txt'
running build_scripts
creating C:\dev\couchapp\build\bdist.win32
creating C:\dev\couchapp\build\bdist.win32\winexe
creating C:\dev\couchapp\build\bdist.win32\winexe\collect-2.7
creating C:\dev\couchapp\build\bdist.win32\winexe\bundle-2.7
creating C:\dev\couchapp\build\bdist.win32\winexe\temp
creating C:\dev\couchapp\dist
*** searching for required modules ***
Traceback (most recent call last):
  File "setup.py", line 214, in <module>
    main()
  File "setup.py", line 211, in main
    setup(**options)
  File "C:\Python27\lib\distutils\core.py", line 151, in setup
    dist.run_commands()
  File "C:\Python27\lib\distutils\dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "C:\Python27\lib\distutils\dist.py", line 972, in run_command
    cmd_obj.run()
  File "C:\Python27\lib\site-packages\py2exe\build_exe.py", line 243, in run
    self._run()
  File "C:\Python27\lib\site-packages\py2exe\build_exe.py", line 296, in _run
    self.find_needed_modules(mf, required_files, required_modules)
  File "C:\Python27\lib\site-packages\py2exe\build_exe.py", line 1306, in find_n
eeded_modules
    mf.import_hook(f)
  File "C:\Python27\lib\site-packages\py2exe\mf.py", line 719, in import_hook
    return Base.import_hook(self,name,caller,fromlist,level)
  File "C:\Python27\lib\site-packages\py2exe\mf.py", line 136, in import_hook
    q, tail = self.find_head_package(parent, name)
  File "C:\Python27\lib\site-packages\py2exe\mf.py", line 204, in find_head_pack
age
    raise ImportError, "No module named " + qname
ImportError: No module named http_parser

C:\dev\couchapp>
```
any hints?

**Comment by broerse** [comment]
Installing Microsoft Visual C++ Compiler for Python 2.7
		http://www.microsoft.com/en-us/download/details.aspx?id=44266

helped with `pip install http-parser` and `pip install restkit`.

Not I have `ImportError: No module named restkit.manager` but it will not pip. Looking now....

**Comment by broerse** [comment]
If out-comment `restkit.manager` in setup.py I get an exe.

```
C:\dev\couchapp\dist>couchapp version
Couchapp (version 1.0.1)
Copyright 2008-2010 Beno├«t Chesneau <benoitc@e-engura.org>
Licensed under the Apache License, Version 2.0.
```

`restkit.manager` will be needed for something. It is always the managers getting in the way :smile: any hints?

**Comment by iblis17** [comment]
Hi @broerse `restkit.manger` has gone long long time ago. 

I have removed it in my (PR)[https://github.com/couchapp/couchapp/pull/187/files#diff-2eeaed663bd0d25b7e608891384b7298L170] :smile:

**Comment by broerse** [comment]
O.K.  but I try to create the latest stable release (1.0.1). Can I just remove it? Should a new stable version be released?

**Comment by iblis17** [comment]
Oh. In release 1.0.1,  simply removing it shoud work fine.

About the new release .... ping @BigBlueHat

**Comment by broerse** [comment]
@iblis17 @BigBlueHat I have now build the latest version (1.0.1) for Windows 32 bit. (Only changes I made are out-commenting `restkit.manager` and changing version number in the Inno-Setup file")

Where do I upload the file for https://couchapp.readthedocs.org/en/latest/couchapp/install.html#installing-on-windows ?


Should it be a .zip like https://couchapp.readthedocs.org/en/latest/couchapp/install.html#installing-on-windows ?

**Comment by broerse** [comment]
@BigBlueHat next to the latest 1.0.1 stable release it would be nice if I can compile a new Stable version from 2015 and not 2011 for the windows users. Are there plans for a new stable release?

**Comment by iblis17** [comment]
@BigBlueHat IMO, we can use the [release page](https://github.com/couchapp/couchapp/releases).
It seems that the [github download page](https://github.com/couchapp/couchapp/downloads) is deprecated.

**Comment by broerse** [comment]
@iblis17 Yes you can now find it under: `Edit release notes`

**Comment by broerse** [comment]
@iblis17 @BigBlueHat It took me a while to understand that is where I can upload the file for you to. Is is now on https://github.com/broerse/couchapp/releases/tag/1.0.1 . A PR for this file is to advanced for GitHub yet ;-)

**Comment by iblis17** [comment]
:+1:

**Comment by broerse** [comment]
It compiled O.K. but it gives me "2015-10-25 07:32:05 [CRITICAL] thread isn't a socketpool backend". Did I miss some socketpool lib? The 1.0.0 works on the same backend.

**Comment by iblis17** [comment]
Hmm.. `socketpool` is required by `restkit`. So.. how about checking `restkit` compiled properly?

**Comment by broerse** [comment]
@iblis17 I out-commented `restkit.manager`.

Did you see the mail I tried to sent you?

**Comment by iblis17** [comment]
Comment out it is ok. 
The lastest verions of `restkit` do not contain `restkit.manager`. FYI: https://github.com/benoitc/restkit/tree/master/restkit.

And `socketpool` is one of its [dependencies](https://github.com/benoitc/restkit/blob/master/requirements.txt). So ... what'is the output of `pip freeze` in your enviroment?

**Comment by broerse** [comment]
@iblis17 In my mail you get access to my environment.

pip freeze:
====
```
Brownie==0.5.1
PyYAML==3.11
argh==0.26.1
http-parser==0.8.3
pathtools==0.1.2
py2exe==0.6.9
pywin32==219
restkit==4.2.2
socketpool==0.5.3
watchdog==0.8.3
```

**Comment by iblis17** [comment]
Oh... :confused: looks fine on `pip freeze`

Let's check the `python2 -m py2exe.mf -d Couchapp.py`.
Here is a part of mine output:
```
...
m socket                    C:\Python27\lib\socket.py
P socketpool                C:\Python27\lib\site-packages\socketpool-0.5.3-py2.7
.egg\socketpool\__init__.py
m socketpool.conn           C:\Python27\lib\site-packages\socketpool-0.5.3-py2.7
.egg\socketpool\conn.py
m socketpool.pool           C:\Python27\lib\site-packages\socketpool-0.5.3-py2.7
.egg\socketpool\pool.py
m socketpool.util           C:\Python27\lib\site-packages\socketpool-0.5.3-py2.7
.egg\socketpool\util.py
...
```

**Comment by broerse** [comment]
Why not take a look on the server yourself. Account is in your mail.

```
m socket                    C:\Python27\lib\socket.py
P socketpool
 C:\Python27\lib\site-packages\socketpool\__init__.py
m socketpool.conn           C:\Python27\lib\site-packages\socketpool\conn.py
m socketpool.pool           C:\Python27\lib\site-packages\socketpool\pool.py
m socketpool.util           C:\Python27\lib\site-packages\socketpool\util.py
```

Thanks,

- Martin

**Comment by broerse** [comment]
@iblis17 Did you find the missing module?

**Comment by iblis17** [comment]
@broerse Hi. sorry for the lag. :scream: 

Actually i cannot connect to your server( maybe your firewall block me), so ... could you help me check the 'couchpp/dist/library.zip' ?

Is there a dir `socketpool` in the zip file?
If it exists, please show me it content :smile: 
Hope that there is a `backend_thread.py`.

If the `backend_thread.py` exists, please check the `import threading` working in your python shell.

**Comment by broerse** [comment]
There is no firewall put up by me. The server is on Amazon Frankfurt.

There is a socketpool containing:

```
10/24/2015  11:43 AM             3,335 conn.pyc
10/24/2015  11:43 AM             5,760 pool.pyc
10/24/2015  11:43 AM             3,994 util.pyc
10/24/2015  11:43 AM               270 __init__.pyc
```

there is no `backend_thread.py`

**Comment by iblis17** [comment]
(Y) we got the root cause! :tada: 

How about adding `socketpool` to `py2exe` 's packages in `setup.py`?

**Comment by broerse** [comment]
🎂 It seem to fix the problem! Will run some tests before I upload this
version. Will create a branch also so we can lookup changes made to compile
1.0.1.

**Comment by broerse** [comment]
Changes made to compile 1.0.1 for Windows 32 bit : https://github.com/broerse/couchapp/commit/84d3998c74b667430be7b0f8d8134a9e843502b0

Test upload with 1.0.1: https://martinic.cloudant.com/bloggrtest/_design/bloggrtest/_rewrite/ (Ember on CouchDB)

Install can be downloaded now from: https://github.com/broerse/couchapp/releases/tag/1.0.1

Thanks @iblis17 . @BigBlueHat can you publish this?

**Comment by iblis17** [comment]
:tada: :tada: :tada:

**Comment by BigBlueHat** [comment]
@broerse great work! I've added the .zip file to the release page:
https://github.com/couchapp/couchapp/releases/tag/1.0.1

It has some encoding problems with @benoitc's name, and we'll need to make some improvements to it over time--as well as loop in @iblis17 fabulous build work as the foundation for future builds, but this'll do the trick for Windows users for now and I'm most grateful! :smile: 

Thanks for your patience too--I've been traveling quite a bit and am only just now catching up. :airplane:

**Comment by BigBlueHat** [comment]
@broerse's here's what the encoding problem looks like:
```
Couchapp (version 1.0.1)
Copyright 2008-2010 Beno├«t Chesneau <benoitc@e-engura.org>
Licensed under the Apache License, Version 2.0.
```

Also, the next release should include more names, probably. :wink:

**Comment by broerse** [comment]
Yes I was thinking @benoitc's name change would not make it a 1.0.1 

Will comment later on 1.0.2 or 1.1.0 releases.

Thanks!
