### ISSUE TITLE
Cleanup the high number of ways to "start" a CouchApp with `couchapp`

### ISSUE THREAD

**Issue by BigBlueHat** [couchapp/couchapp#198]
Right now, you can us any of the following commands each with their own unique way of doing things...

##### `couchapp init`
Directory contents:
```
.couchappignore  .couchapprc
```

##### `couchapp startapp`
:bug: Fails with error `2015-11-13 10:41:58 [ERROR] couchapp error: Can't start an app, name or path is missing`, but generates the same as `couchapp init` above.

##### `couchapp startapp NAME`
`2015-11-13 10:44:30 [INFO] c:\Users\Benjamin\Documents\GitHub\anno-mail\temp\NAME created.`
Creates a `NAME` directory who's contents are:
```
.couchappignore  .couchapprc  _attachments  _id  lists  shows  updates  views
```

##### `couchapp startapp . NAME`
:bug: This is supposed to support passing in a `COUCHAPPDIR` param before `NAME`, but `.` is unsupported...apparently.

Outputs `2015-11-13 10:46:51 [INFO] NAME created.` with a `NAME` directory (which it shouldn't do) which matches the above contents.

##### `couchapp generate NAME`
:bug: This one seems to attempt to use the current directory (if one's unspecified) rather than auto-magically creating a directory for `NAME` in the way that `startapp` does.

Outputs `2015-11-13 10:48:56 [ERROR] couchapp error: Can't create a CouchApp in c:\current\directory: Cannot create a file when that file already exists`

Trying `couchapp generate . NAME` checks `.` against the options lists (which makes sense given the param list. Outputs `2015-11-13 10:50:11 [ERROR] couchapp error: Can't generate . in your couchapp. generator is unknown`

:bug: This also failed...again not doing what `startapp` did:
```
$ couchapp generate app NAME
2015-11-13 10:51:32 [ERROR] couchapp error: Can't create a CouchApp in c:\current\directory: Cannot create a file when that file already exists
```

This worked, however.
```
$ couchapp generate app NAME NAME
2015-11-13 10:51:54 [INFO] NAME generated.
```

But the directory contents are different than `startapp`'s:
```
README.md  _attachments  _id  couchapp.json  language  lists  shows  updates  vendor  views
```

### Proposal
* deprecate `startapp`
* "upgrade" `init` to replace `startapp` and `generate app`
  * have it use the `generate app` system with the `--template` option
* (possibly) deprecate `generate app` -- keep it focused on generating the other things
* simplify base template for initialized app, so it matches what `startapp` does now--so, no jquery, no vendor, no .js, .html, or .css

**Comment by BigBlueHat** [comment]
Here's a comparison of the 3 varied outputs we have now.
```
|~generate-app/
| |~_attachments/
| | |~script/
| | | `-app.js
| | |~style/
| | | `-main.css
| | `-index.html
| |~lists/
| |~shows/
| |~updates/
| |~vendor/
| | `~couchapp/
| |   |~_attachments/
| |   | |-jquery.couch.app.js
| |   | |-jquery.couch.app.util.js
| |   | |-jquery.couchForm.js
| |   | |-jquery.couchLogin.js
| |   | |-jquery.couchProfile.js
| |   | |-jquery.mustache.js
| |   | `-md5.js
| |   `-metadata.json
| |~views/
| | `~recent-items/
| |   `-map.js
| |-_id
| |-couchapp.json
| |-language
| |-README.md
```
 - lots of "extra" stuff
 - lacks .couchapprc and .couchappignore

```
|~init/
  |~.couchappignore
  |~.couchapprc
```
 - has only the two things `generate app` is missing

```
`~startapp/
  |~.couchappignore
  |~.couchapprc
  |~_attachments/
  |~lists/
  |~shows/
  |~updates/
  |~views/
  `-_id
```
 - more "ideal" start point--just a stub of what you actually need to begin building a CouchApp

This last bit is what I think we should keep:
 - rename it to `couchapp init` (from `startapp`)
 - make it avoid existing files and directories with matching names
 - make it work on a subdirectory: `couchpp init new-app` currently fails with `directory does not exist` error

**Comment by iblis17** [comment]
Hmmm.. I think we should redefine the goal of `generate app --template`. I cannot determine the difference between `clone`.

If  `generate app` means doing cloning really, I will agree to deprecate it, and extend the ability of clone.

**Comment by iblis17** [comment]
@BigBlueHat  Hmm... I re-read your post again and dug into our codebase.

I think the original design is _we provide different level of starting a couchapp_.

original design says that:
- `init` for _creating the essential element for a couchapp_
- `startapp`: _i need a skeleton_ (also, it's an alias of `$ couchapp generate startapp`)
- `generate app`: _i need a boilerplate! I'm familiar to work with my favorite (custom) vendor_

So the stuff get more and more from `init` to `gen app`.

It's time to decide that do we need to support 3 level of init? 
If yes, we can integrate them into `init`. Maybe make `init` accept more options.
if no, we can implement your proposal -- rename `startapp` to `init` and make it better.
