### ISSUE TITLE
Remove the ability to store `env` (and kids) inside `couchapp.json`

### ISSUE THREAD

**Issue by BigBlueHat** [couchapp/couchapp#200]
Until this PR #195, I had no idea one could put `env` contents in `couchapp.json`. This seems to invite risk of publishing more than one wants--putting public facing content (name, description) content next to private, unencrypted content (`env.default.db`, etc.).

I'd propose we remove `couchapp.json` from [`config.py` line 65](https://github.com/couchapp/couchapp/blob/210f1cc6dc795bdf67eac37e85789450918a2301/couchapp/config.py#L65).

**Comment by iblis17** [comment]
I it's reasonable for carrying something like [hooks and vendor handler](http://couchapp.readthedocs.org/en/latest/couchapp/extends.html#hooks) through `couchapp.json`.

May we can consider some trade-off: just prevent `env` loaded from `couchapp.json` only.

**Comment by iblis17** [comment]
@BigBlueHat I will implement the trade-off version if #176 completes.

**Comment by iblis17** [comment]
@BigBlueHat please try out [branch issue-200](https://github.com/couchapp/couchapp/tree/issue-200) :)

**Comment by BigBlueHat** [comment]
Perfect! Great thinking on the warning message--and having the details of where the information *should* go. Super fab! :dancer:

**Comment by iblis17** [comment]
I will document this and send PR in few days later. :)

**Comment by BigBlueHat** [comment]
:heart:

**Comment by iblis17** [comment]
Merged via  f2955e9
