### ISSUE TITLE
(1.0.2 win standalone) couchapp push testdb: thread isn't a socketpool backend

### ISSUE THREAD

**Issue by kastrup312** [couchapp/couchapp#224]
Hi 
I get an error when attempting to push my first couchapp 'helloworl' back to couch:

_2016-02-09 01:20:27 [CRITICAL] thread isn't a socketpool backend

Traceback (most recent call last):
  File "couchapp\dispatch.pyc", line 45, in dispatch
  File "couchapp\dispatch.pyc", line 92, in _dispatch
  File "couchapp\commands.pyc", line 72, in push
  File "couchapp\config.pyc", line 159, in get_dbs
  File "couchapp\client.pyc", line 219, in __init__
  File "couchapp\client.pyc", line 66, in __init__
  File "restkit\resource.pyc", line 72, in __init__
  File "restkit\client.pyc", line 136, in __init__
  File "restkit\session.pyc", line 18, in get_session
  File "socketpool\pool.pyc", line 53, in __init__
  File "socketpool\util.pyc", line 71, in load_backend
ImportError: thread isn't a socketpool backend

Note:

- I have installed CouchApp for Windows 'Standalone Executable 1.0.2'
- I have not installed python or anything else than couchdb
- couchdb works fine (incl. html attachments)
- I have created a simple hello world application (as explained here: http://couchapp.readthedocs.org/en/latest/couchapp/gettingstarted.html)

Do you have any suggestions to how I proceed?

**Comment by iblis17** [comment]
Hi @kastrup312 !

Err... That's my fall ... maybe i missed something to package with windows standalone exe.

I fixed it. please give a try for [the new exe build](https://ci.appveyor.com/project/iblis17/couchapp/build/job/71cd6qktd7m7bwu8/artifacts). If it works fine, we will do a new release. (I need a brown-bag ...

**Comment by kastrup312** [comment]
Hi
Thanks for the reply and the update in git. I could not find a updated windows installer, so I tried to build one myself. Unfortunately I ran into a problem.
After installing all the prerequities I was able to run 'python setup.py build -c mingw32' without any problem. When running 'python setup.py py2exe -b 2' Immediately after that, I got the error below.
Can you give me any advice on that, or even better if anyone could build the windows installer, as I have no python experience.
Regards, Kent
Error (output of running 'python setup.py py2exe -b 2'):
	C:\couchapp build\couchapp-master>python setup.py py2exe -b 2	running py2exe	running build_py	running egg_info	writing requirements to Couchapp.egg-info\requires.txt	writing Couchapp.egg-info\PKG-INFO	writing top-level names to Couchapp.egg-info\top_level.txt	writing dependency_links to Couchapp.egg-info\dependency_links.txt	reading manifest file 'Couchapp.egg-info\SOURCES.txt'	reading manifest template 'MANIFEST.in'	warning: no files found matching '*' under directory 'doc'	writing manifest file 'Couchapp.egg-info\SOURCES.txt'	running build_scripts	creating C:\couchapp build\couchapp-master\build\bdist.win32	creating C:\couchapp build\couchapp-master\build\bdist.win32\winexe	creating C:\couchapp build\couchapp-master\build\bdist.win32\winexe\collect-2.7	creating C:\couchapp build\couchapp-master\build\bdist.win32\winexe\bundle-2.7	creating C:\couchapp build\couchapp-master\build\bdist.win32\winexe\temp	creating C:\couchapp build\couchapp-master\dist	*** searching for required modules ***	Traceback (most recent call last):	  File "setup.py", line 174, in <module>		main()	  File "setup.py", line 171, in main		setup(**options)	  File "C:\Python27\lib\distutils\core.py", line 151, in setup		dist.run_commands()	  File "C:\Python27\lib\distutils\dist.py", line 953, in run_commands		self.run_command(cmd)	  File "C:\Python27\lib\distutils\dist.py", line 972, in run_command		cmd_obj.run()	  File "C:\Python27\lib\site-packages\py2exe\build_exe.py", line 243, in run		self._run()	  File "C:\Python27\lib\site-packages\py2exe\build_exe.py", line 296, in _run		self.find_needed_modules(mf, required_files, required_modules)	  File "C:\Python27\lib\site-packages\py2exe\build_exe.py", line 1306, in find_n	eeded_modules		mf.import_hook(f)	  File "C:\Python27\lib\site-packages\py2exe\mf.py", line 719, in import_hook		return Base.import_hook(self,name,caller,fromlist,level)	  File "C:\Python27\lib\site-packages\py2exe\mf.py", line 136, in import_hook		q, tail = self.find_head_package(parent, name)	  File "C:\Python27\lib\site-packages\py2exe\mf.py", line 204, in find_head_pack	age		raise ImportError, "No module named " + qname	ImportError: No module named http_parser

Date: Mon, 8 Feb 2016 22:18:08 -0800

**Comment by iblis17** [comment]
:-o. [Here](https://ci.appveyor.com/api/buildjobs/71cd6qktd7m7bwu8/artifacts/Output/couchapp-1.0.2-win32-py27-148197c.exe) is direct download link.

----

The error message says that `http_parser` not found which is our dependency. IIRC, that is a `py2exe` issue: all dependency can not install in zipped format, `egg`. So you need to remove all them first, then reinstall them in following instruction. The option `-Z` is the key. 
```
python -m easy_install -Z restkit==4.2.2 watchdog==0.6.0
```

**Comment by iblis17** [comment]
The new binary has been uploaded to github download page.
@kastrup312 Thanks for your reporting.
