### ISSUE TITLE
couchapp-1.0.2-win32.exe supposely infected by virus

### ISSUE THREAD

**Issue by gdelfino** [couchapp/couchapp#235]
I would just like to report that the CouchApp installer for windows (couchapp-1.0.2-win32.exe) is triggering a virus alert by "Symantec Endpoint Protection". I am almost sure that this is not the case, but still wanted to report it in case something can be done to prevent this.

**Comment by iblis17** [comment]
:-o Would you post the report contains more detail about that?
I just tried a scan service, and ... none of them screaming:
https://www.virustotal.com/zh-tw/file/44e8e467868972265dd17c387b96e9bbdadf56c3780194028b69aff4895d34fe/analysis/

**Comment by iblis17** [comment]
Feel free to reopen if the virus alert still exists.
