### ISSUE TITLE
Re-import RTD couchapp project

### ISSUE THREAD

**Issue by iblis17** [couchapp/couchapp#236]
Hi @benoitc @BigBlueHat !

I want to create a doc branch on RTD, but there is an issue of RTD filed here:
https://github.com/rtfd/readthedocs.org/issues/2163.
The issue has been opened for a long time but no response.

I guess the workaround is "Delete the couchapp project than import it again".
May I give this workaround a try?

**Comment by BigBlueHat** [comment]
Go for it, @iblis17!

And thanks for all you're doing! :cake:

**Comment by iblis17** [comment]
The version list came back!

@BigBlueHat  The webhook setup need your help! I do not have the webhook permission on this repo.

**Comment by iblis17** [comment]
http://couchapp.readthedocs.io/en/stable-1.0/ 
We get stable branch now! :tada:

**Comment by BigBlueHat** [comment]
Great work @iblis17! You've got admin on this repo now. Enjoy!

**Comment by iblis17** [comment]
Wow thanks!
