### ISSUE TITLE
Couchdb 2.0 Support

### ISSUE THREAD

**Issue by chaitanya9186** [couchapp/couchapp#238]

**Comment by iblis17** [comment]
Hi @chaitanya9186 
Seems that there is not any api we need deprecated. Any idea about new features we want to add?

**Comment by chaitanya9186** [comment]
I am fairly new to Couchdb. 
I didn't try using couchapp yet.
And also is there any support for Single page applications like apps using Angular2.

**Comment by iblis17** [comment]
Basically, CouchDB is framework-neutral. Just put your files in correct attachment/path and web server of couch will serve it.

For some advance usages, e.g. integrating [SSE](http://docs.couchdb.org/en/2.0.0/api/database/changes.html#event-source) with front-end frameworks' data binding, @BigBlueHat has done that with VueJs, IIRC. And the other frameworks... AFAIK: no.

**Comment by chaitanya9186** [comment]
Thanks @iblis17 
Could you able to point me to the repo (if possible).

**Comment by iblis17** [comment]
Oh... It's based on pouchdb: https://github.com/BigBlueHat/vue-pouchdb/

**Comment by BigBlueHat** [comment]
Yeah, in that code http://pouchdb.com/ is serving as the Apache CouchDB client and providing all the SSE / _changes listening goodness (as you can see from the minimal Vue.js integration code).

@chaitanya9186 you might want to join the [CouchApp-related Mailing List](http://mail-archives.apache.org/mod_mbox/couchdb-couchapp/) and post more questions there.

AFAIK nothing significant (with regard to the [Design Doc](docs.couchdb.org/en/2.0.0/couchapp/ddocs.html) system has changed in Apache CouchDB 2.0 that would make this library (nor all the other design doc / couchapp publishing tools) break in anyway.

It should just work. :smile: 

Consequently, I'm going to close this issue, in favor of moving the conversation to the mailing list.

Thanks for writing though @chaitanya9186!
