### ISSUE TITLE
init command does not work 

### ISSUE THREAD

**Issue by leolivier** [couchapp/couchapp#242]
Hi,
I'm trying to create a new couchapp on a raspberry pi 2 and it does not work (despite merge #227) :
```
/mnt/ssd/dev $ couchapp -v -d init naughtapp
2017-01-27 19:21:39 [ERROR] /mnt/ssd/dev/naughtapp directory doesn't exist.
2017-01-27 19:21:39 [CRITICAL] [Errno 2] No such file or directory: '/mnt/ssd/dev/naughtapp/.couchapprc'

```
If I create myself the directory, I only get 2 files created (which is not enough compared to what the getting started doc says):
```
/mnt/ssd/dev $ mkdir naughtapp
/mnt/ssd/dev $ couchapp -v -d init naughtapp
/mnt/ssd/dev $ tree -a naughtapp/
naughtapp/
├── .couchappignore
└── .couchapprc

0 directories, 2 files
```
So what's going wrong?

**Comment by iblis17** [comment]
hmm.. I cannot reproduce that error on master branch.
Which version of couchapp are you using?

**Comment by leolivier** [comment]
couchapp --version
Couchapp (version 1.0.2)
Copyright 2008-2010 Benoît Chesneau <benoitc@e-engura.org>
Licensed under the Apache License, Version 2.0.

**Comment by iblis17** [comment]
I guess that  I did not fix the initiation of new dir correctly until #229 merged.
How about giving master branch a try:
```
pip uninstall couchapp   # uninstall 1.0.2 first
pip install git+https://github.com/couchapp/couchapp.git
```

**Comment by leolivier** [comment]
Works great this way!
Thanks iblis17
